
version: "3.9"
services:
  bot:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env
    command: ["bash", "-lc", "pip install --no-cache-dir -r requirements.txt && python bot/main.py"]
    restart: unless-stopped
