
version: "3.9"
services:
  bot:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./bot:/app
      - ./bot/data:/app/data
    env_file: .env
    command: ["python", "main.py"]
    restart: unless-stopped
